# Generated by Django 4.2.1 on 2024-04-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='event_thumbnail/')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event')),
            ],
        ),
    ]
