# Generated by Django 4.2.1 on 2024-04-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_eventthumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventthumbnail',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
