# Generated by Django 4.2.1 on 2024-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_remove_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketprice',
            name='max_age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventticketprice',
            name='min_age',
            field=models.DateField(),
        ),
    ]
