# Generated by Django 4.2.1 on 2024-05-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_image_eventthumbnail_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event')),
            ],
        ),
    ]
