# Generated by Django 4.2.1 on 2024-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_max_age_eventticketprice_max_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticketprice',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventticketprice',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
    ]
