# Generated by Django 4.2.1 on 2024-05-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_eventticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketprice',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingMebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.familymember')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.ticket')),
            ],
        ),
    ]
