# Generated by Django 4.2.1 on 2024-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_eventticketprice_max_age_eventticketprice_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(default=0),
        ),
    ]
