# Generated by Django 4.2.1 on 2024-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_ticket_user_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingMebers',
            new_name='BookingMembers',
        ),
    ]
