# Generated by Django 4.2.1 on 2024-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_remove_event_capacity_remove_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticketprice',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventticketprice',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='eventticketprice',
            name='max_dob',
        ),
        migrations.RemoveField(
            model_name='eventticketprice',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='eventticketprice',
            name='min_dob',
        ),
        migrations.RemoveField(
            model_name='eventticketprice',
            name='price',
        ),
        migrations.AddField(
            model_name='eventticketprice',
            name='guest_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventticketprice',
            name='member_price',
            field=models.IntegerField(default=0),
        ),
    ]
