# Generated by Django 4.2.1 on 2024-05-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmembers',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.familymember'),
        ),
    ]
