# Generated by Django 4.2.1 on 2024-05-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_remove_eventticketprice_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticketprice',
            old_name='guest_price',
            new_name='non_member_price',
        ),
        migrations.AddField(
            model_name='eventticketprice',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event'),
        ),
    ]
