# Generated by Django 4.2.1 on 2024-05-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_rename_guest_price_eventticketprice_non_member_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticketprice',
            old_name='non_member_price',
            new_name='guest_price',
        ),
    ]
