# Generated by Django 4.2.1 on 2024-05-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_bookingmembers_family_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketprice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.event'),
        ),
    ]
