# Generated by Django 4.2.1 on 2024-05-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_alter_eventticketprice_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventImages',
            new_name='EventImagesBrochure',
        ),
    ]
