# Generated by Django 4.2.1 on 2024-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_rename_non_member_price_eventticketprice_guest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
