# Generated by Django 4.2.1 on 2024-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_bookingmembers_member_alter_bookingmembers_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
