# Generated by Django 4.2.1 on 2024-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_alter_userprofile_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
