# Generated by Django 4.2.1 on 2024-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_ticket_paid_amount_alter_userprofile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='Tickets/'),
        ),
    ]
