# Generated by Django 4.2.1 on 2024-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_ticket_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
