# Generated by Django 4.2.1 on 2024-05-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0020_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
