# Generated by Django 4.2.1 on 2024-05-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_news_news_photos_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_photos_videos',
            new_name='NewsPhotosVideosForm',
        ),
    ]
