# Generated by Django 4.2.1 on 2024-05-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0023_rename_news_photos_videos_newsphotosvideosform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPhotosVideosForm',
            new_name='NewsPhotosVideos',
        ),
    ]
