# Generated by Django 4.2.1 on 2024-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0024_rename_newsphotosvideosform_newsphotosvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
