# Generated by Django 4.2.1 on 2024-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0025_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsphotosvideos',
            name='video',
        ),
        migrations.AddField(
            model_name='newsphotosvideos',
            name='video_link',
            field=models.URLField(blank=True, help_text='Enter YouTube video link', null=True),
        ),
    ]
