# Generated by Django 4.2.1 on 2024-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0026_remove_newsphotosvideos_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphotosvideos',
            name='video_link',
            field=models.CharField(blank=True, help_text='Enter YouTube video link', max_length=255, null=True),
        ),
    ]
