# Generated by Django 4.2.1 on 2024-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_alter_newsphotosvideos_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended Size 1280 x 720 (landscape)', null=True, upload_to='news_thumbnail/'),
        ),
    ]
