# Generated by Django 4.2.1 on 2024-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0029_alter_eventthumbnail_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming ', 'Upcoming '), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='upcoming', max_length=10),
        ),
    ]
