# Generated by Django 4.2.1 on 2024-05-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_alter_event_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='is_publish',
        ),
    ]
