# Generated by Django 4.2.1 on 2024-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0033_rename_is_active_event_is_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, help_text='Enter YouTube video link', max_length=255, null=True)),
            ],
        ),
    ]
