# Generated by Django 4.2.1 on 2024-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0035_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming '), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='upcoming', max_length=10),
        ),
    ]
